# ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: radical0618

# ??mybatis-plus?xml??????
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#shiro??
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

# ???????jwt?????
radical:
  jwt:
    # ?????????
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token?????7??????
    expire: 604800
    header: token